#!/usr/bin/env python3
"""
Script to generate point clouds from RGB images and camera intrinsics using depth_anything_3 and open3d.
Reads from zarr files generated by gen_demonstration_metaworld.sh and saves point clouds back to zarr.
python scripts/depth_anything_wrapper.py \
    --device cuda \
    --batch_size 10 \
    --num_points 4096 \
    --zarr_path 3D-Diffusion-Policy/data/metaworld_pick-place_expert.zarr
"""

import argparse
import os
import zarr
import numpy as np
import torch
import open3d as o3d
import cv2
from tqdm import tqdm
from termcolor import cprint
from depth_anything_3.api import DepthAnything3
import pytorch3d.ops as torch3d_ops



def cammat2o3d(cam_mat, width, height):
    """Convert numpy camera intrinsic matrix to Open3D format."""
    cx = cam_mat[0, 2]
    fx = cam_mat[0, 0]
    cy = cam_mat[1, 2]
    fy = cam_mat[1, 1]
    return o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)

def point_cloud_sampling(point_cloud:np.ndarray, num_points:int, method:str='fps'):
    """
    support different point cloud sampling methods
    point_cloud: (N, 6), xyz+rgb or (N, 3), xyz
    """
    if num_points == 'all': # use all points
        return point_cloud
    
    if point_cloud.shape[0] <= num_points:
        # cprint(f"warning: point cloud has {point_cloud.shape[0]} points, but we want to sample {num_points} points", 'yellow')
        # pad with zeros
        point_cloud_dim = point_cloud.shape[-1]
        point_cloud = np.concatenate([point_cloud, np.zeros((num_points - point_cloud.shape[0], point_cloud_dim))], axis=0)
        return point_cloud

    if method == 'uniform':
        # uniform sampling
        sampled_indices = np.random.choice(point_cloud.shape[0], num_points, replace=False)
        point_cloud = point_cloud[sampled_indices]
    elif method == 'fps':
        # fast point cloud sampling using torch3d
        point_cloud = torch.from_numpy(point_cloud).unsqueeze(0).cuda()
        num_points = torch.tensor([num_points]).cuda()
        # remember to only use coord to sample
        _, sampled_indices = torch3d_ops.sample_farthest_points(points=point_cloud[...,:3], K=num_points)
        point_cloud = point_cloud.squeeze(0).cpu().numpy()
        point_cloud = point_cloud[sampled_indices.squeeze(0).cpu().numpy()]
    else:
        raise NotImplementedError(f"point cloud sampling method {method} not implemented")

    return point_cloud

def depth_to_pointcloud(depth, intrinsics, rgb_image=None):
    """
    Convert depth map and camera intrinsics to point cloud using Open3D.
    
    Args:
        depth: (H, W) float32 depth map
        intrinsics: (3, 3) float32 camera intrinsic matrix
        rgb_image: (H, W, 3) uint8 RGB image (optional)
    
    Returns:
        point_cloud: (N, 3) or (N, 6) float32 point cloud (xyz or xyz+rgb)
    """
    height, width = depth.shape
    
    # Convert to Open3D format
    o3d_intrinsics = cammat2o3d(intrinsics, width, height)
    o3d_depth = o3d.geometry.Image(depth.astype(np.float32))
    
    if rgb_image is not None:
        # Create RGBD image
        # depth_scale=1.0 because Depth Anything outputs depth in meters (not millimeters)
        o3d_color = o3d.geometry.Image(rgb_image.astype(np.uint8))
        rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
            o3d_color, o3d_depth, depth_scale=1.0, depth_trunc=1000.0, convert_rgb_to_intensity=False
        )
        # Generate point cloud with colors
        pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, o3d_intrinsics)
    else:
        # Generate point cloud without colors
        # depth_scale=1.0 because Depth Anything outputs depth in meters (not millimeters)
        pcd = o3d.geometry.PointCloud.create_from_depth_image(o3d_depth, o3d_intrinsics, depth_scale=1.0)
    
    # Convert to numpy array
    points = np.asarray(pcd.points)  # (N, 3)
    
    if rgb_image is not None and pcd.has_colors():
        colors = np.asarray(pcd.colors)  # (N, 3) in [0, 1]
        # Convert colors to [0, 255] range
        colors = (colors * 255).astype(np.uint8)
        point_cloud = np.concatenate([points, colors], axis=1)  # (N, 6)
    else:
        point_cloud = points  # (N, 3)
    
    return point_cloud


def align_depth_per_frame(predicted_depth, gt_depth):
    """
    Align predicted depth to ground truth using least squares scale and shift.
    
    aligned_depth = scale * predicted_depth + shift
    
    Args:
        predicted_depth: (H, W) predicted depth map
        gt_depth: (H, W) ground truth depth map
    
    Returns:
        aligned_depth: (H, W) aligned depth map
        scale, shift: alignment parameters
    """
    # Create valid mask (positive depths)
    mask = (gt_depth > 0) & (predicted_depth > 0)
    
    if mask.sum() < 10:
        # Not enough valid pixels, return original
        return predicted_depth, 1.0, 0.0
    
    pred_valid = predicted_depth[mask].flatten()
    gt_valid = gt_depth[mask].flatten()
    
    # Solve least squares: gt = scale * pred + shift
    A = np.stack([pred_valid, np.ones_like(pred_valid)], axis=1)
    result, _, _, _ = np.linalg.lstsq(A, gt_valid, rcond=None)
    scale, shift = result
    
    aligned_depth = scale * predicted_depth + shift
    
    return aligned_depth, scale, shift


def process_zarr_file(zarr_path, device='cuda', batch_size=10, num_points=4096):
    """
    Process zarr file: read images and intrinsics, generate depth maps, create point clouds.
    
    Args:
        zarr_path: Path to input zarr file
        device: Device to use for depth_anything_3 ('cuda' or 'cpu')
        batch_size: Batch size for depth inference
        num_points: Number of points to sample in each point cloud (default: 4096)
    """
    cprint(f'Processing zarr file: {zarr_path}', 'cyan')
    
    # Open zarr file in read mode
    root = zarr.open(zarr_path, mode='r')
    
    if 'data' not in root:
        raise ValueError(f"No 'data' group found in zarr file at {zarr_path}")
    
    data_group = root['data']
    
    # Load required arrays
    if 'img' not in data_group:
        raise ValueError(f"No 'img' dataset found in zarr file")
    img_array = data_group['img']
    
    if 'camera_intrinsics' not in data_group:
        raise ValueError(f"No 'camera_intrinsics' dataset found in zarr file")
    camera_intrinsics_array = data_group['camera_intrinsics']
    
    # Load episode_ends from meta
    if 'meta' not in root or 'episode_ends' not in root['meta']:
        raise ValueError(f"No 'meta/episode_ends' found in zarr file")
    episode_ends = root['meta']['episode_ends'][:]
    
    num_samples = img_array.shape[0]
    img_height, img_width = img_array.shape[1], img_array.shape[2]
    
    cprint(f'Found {num_samples} samples, image size: {img_height}x{img_width}', 'green')
    cprint(f'Number of episodes: {len(episode_ends)}', 'green')
    
    # Initialize depth_anything_3 model
    cprint('Loading depth_anything_3 model...', 'yellow')
    model = DepthAnything3.from_pretrained("depth-anything/DA3NESTED-GIANT-LARGE")
    model = model.to(device=device)
    model.eval()
    
    # Prepare temporary directory for images (depth_anything_3 needs file paths)
    import tempfile
    import imageio
    temp_dir = tempfile.mkdtemp()
    
    try:
        # Process images in batches
        all_point_clouds = []
        all_depths = []
        
        cprint('Processing images and generating depth maps...', 'yellow')
        for batch_start in tqdm(range(0, num_samples, batch_size), desc="Processing batches"):
            batch_end = min(batch_start + batch_size, num_samples)
            batch_indices = list(range(batch_start, batch_end))
            
            # Save images temporarily for depth_anything_3
            image_paths = []
            for idx in batch_indices:
                img = img_array[idx]  # (H, W, 3) uint8
                img_path = os.path.join(temp_dir, f"img_{idx}.png")
                imageio.imwrite(img_path, img)
                image_paths.append(img_path)
            
            # Run depth inference with MuJoCo intrinsics
            with torch.no_grad():
                # Get MuJoCo intrinsics for this batch
                batch_intrinsics_mujoco = np.stack([camera_intrinsics_array[idx] for idx in batch_indices], axis=0)  # (batch_size, 3, 3)
                
                # Pass MuJoCo intrinsics to Depth Anything
                prediction = model.inference(image_paths, intrinsics=batch_intrinsics_mujoco)
            
            # prediction.depth: [N, H, W] float32
            batch_depths = np.asarray(prediction.depth)  # (batch_size, H, W)
            
            cprint(f'Batch depths shape: {batch_depths.shape}', 'cyan')
            if batch_start == 0:
                cprint(f'Using MuJoCo intrinsics:\n{batch_intrinsics_mujoco[0]}', 'cyan')
            
            # Generate point clouds for each image in batch
            for i, idx in enumerate(batch_indices):
                depth = batch_depths[i]  # (H, W) - might be 504x504
                # Use the same MuJoCo intrinsics for point cloud generation
                intrinsics = camera_intrinsics_array[idx]  # (3, 3)
                rgb_image = img_array[idx]  # (H, W, 3) - 512x512
                
                # Resize depth to match RGB image size if they don't match
                depth_h, depth_w = depth.shape
                rgb_h, rgb_w = rgb_image.shape[:2]
                if depth.shape != rgb_image.shape[:2]:
                    depth = cv2.resize(depth, (rgb_w, rgb_h), interpolation=cv2.INTER_LINEAR)
                    # No need to adjust intrinsics since we're using the stored MuJoCo intrinsics
                    # which are already for the 512x512 resolution
                
                # Per-frame alignment: align predicted depth to ground truth
                gt_depth = data_group['depth'][idx]
                depth, scale, shift = align_depth_per_frame(depth, gt_depth)
                if batch_start == 0 and i == 0:
                    cprint(f'Sample alignment (frame {idx}): scale={scale:.4f}, shift={shift:.4f}', 'cyan')
                
                # Store aligned depth
                all_depths.append(depth.copy())
                
                # Generate point cloud from aligned depth and intrinsics
                point_cloud = depth_to_pointcloud(depth, intrinsics, rgb_image)
                
                # Sample to exactly num_points
                point_cloud = point_cloud_sampling(point_cloud, num_points, method='fps')
                
                all_point_clouds.append(point_cloud)
        
        # Stack all point clouds and depths
        point_cloud_arrays = np.stack(all_point_clouds, axis=0)  # (num_samples, num_points, 3 or 6)
        depth_arrays = np.stack(all_depths, axis=0)  # (num_samples, H, W)
        
        cprint(f'Generated point clouds shape: {point_cloud_arrays.shape}', 'green')
        cprint(f'Generated depth maps shape: {depth_arrays.shape}', 'green')
        
        # Now save back to zarr maintaining the same structure
        cprint('Saving point clouds and depth maps to zarr...', 'yellow')
        
        # Open zarr file in write mode (or create new one)
        # We'll update the existing point_cloud and depth datasets
        root_write = zarr.open(zarr_path, mode='r+')
        data_group_write = root_write['data']
        
        # Get the existing point_cloud dataset to check its shape and chunks
        if 'point_cloud' in data_group_write:
            existing_pc = data_group_write['point_cloud']
            existing_shape = existing_pc.shape
            existing_chunks = existing_pc.chunks
            existing_dtype = existing_pc.dtype
            
            cprint(f'Existing point_cloud shape: {existing_shape}, chunks: {existing_chunks}, dtype: {existing_dtype}', 'cyan')
            
            # Check if we need to update (shape might be different if num_points changed)
            if point_cloud_arrays.shape != existing_shape:
                cprint(f'Updating point_cloud shape from {existing_shape} to {point_cloud_arrays.shape}', 'yellow')
                # Delete and recreate with new shape
                del data_group_write['point_cloud']
            
            # Determine dtype - use float32 for xyz, or keep existing if it matches
            if point_cloud_arrays.shape[2] == 3:
                pc_dtype = 'float32'
            elif point_cloud_arrays.shape[2] == 6:
                # For xyz+rgb, we might want to keep xyz as float32 and rgb as uint8
                # But zarr doesn't support mixed types, so we'll use float32 for all
                pc_dtype = 'float32'
            else:
                pc_dtype = existing_dtype if 'existing_dtype' in locals() else 'float32'
        else:
            # Create new dataset
            existing_chunks = None
            pc_dtype = 'float32'
        
        # Use same chunk size as original (100, num_points, 3 or 6)
        if existing_chunks is None:
            point_cloud_chunk_size = (100, point_cloud_arrays.shape[1], point_cloud_arrays.shape[2])
        else:
            point_cloud_chunk_size = existing_chunks
        
        # Create or update point_cloud dataset
        compressor = zarr.Blosc(cname='zstd', clevel=3, shuffle=1)
        data_group_write.create_dataset(
            'point_cloud',
            data=point_cloud_arrays,
            chunks=point_cloud_chunk_size,
            dtype=pc_dtype,
            overwrite=True,
            compressor=compressor
        )
        
        cprint(f'Successfully saved point clouds to {zarr_path}', 'green')
        cprint(f'Point cloud shape: {point_cloud_arrays.shape}, dtype: {pc_dtype}', 'green')
        cprint(f'Chunk size: {point_cloud_chunk_size}', 'green')
        
        # Save depth maps
        cprint('Saving depth maps to zarr...', 'yellow')
        
        # Get existing depth dataset info if it exists
        if 'depth' in data_group_write:
            existing_depth = data_group_write['depth']
            existing_depth_shape = existing_depth.shape
            existing_depth_chunks = existing_depth.chunks
            existing_depth_dtype = existing_depth.dtype
            
            cprint(f'Existing depth shape: {existing_depth_shape}, chunks: {existing_depth_chunks}, dtype: {existing_depth_dtype}', 'cyan')
            
            # Check if we need to update (shape might be different)
            if depth_arrays.shape != existing_depth_shape:
                cprint(f'Updating depth shape from {existing_depth_shape} to {depth_arrays.shape}', 'yellow')
                del data_group_write['depth']
                existing_depth_chunks = None
        else:
            existing_depth_chunks = None
        
        # Use same chunk size as original or create new one
        if existing_depth_chunks is None:
            depth_chunk_size = (100, depth_arrays.shape[1], depth_arrays.shape[2])
        else:
            depth_chunk_size = existing_depth_chunks
        
        # Create or update depth dataset
        data_group_write.create_dataset(
            'depth',
            data=depth_arrays,
            chunks=depth_chunk_size,
            dtype='float32',
            overwrite=True,
            compressor=compressor
        )
        
        cprint(f'Successfully saved depth maps to {zarr_path}', 'green')
        cprint(f'Depth shape: {depth_arrays.shape}, dtype: float32', 'green')
        cprint(f'Chunk size: {depth_chunk_size}', 'green')
        
    finally:
        # Clean up temporary directory
        import shutil
        shutil.rmtree(temp_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description='Generate point clouds from RGB images using depth_anything_3')
    parser.add_argument('--zarr_path', type=str, required=True,
                        help='Path to input zarr file (e.g., 3D-Diffusion-Policy/data/metaworld_pick-place_expert.zarr)')
    parser.add_argument('--device', type=str, default='cuda',
                        help='Device to use (cuda or cpu)')
    parser.add_argument('--batch_size', type=int, default=10,
                        help='Batch size for depth inference')
    parser.add_argument('--num_points', type=int, default=4096,
                        help='Number of points to sample in each point cloud')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.zarr_path):
        raise FileNotFoundError(f"Zarr file not found: {args.zarr_path}")
    
    process_zarr_file(
        zarr_path=args.zarr_path,
        device=args.device,
        batch_size=args.batch_size,
        num_points=args.num_points
    )


if __name__ == '__main__':
    main()
